version: "3"

services:
  webserver:
    container_name: tweb
    build: ./src
    image: php:8.0-apache
    volumes:
      - ./src/:/var/www/html
    ports:
      - 8070:80
    depends_on:
      - db
  db:
    container_name: tweb-sql
    image: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sql
  adminer:
    image: adminer
    ports:
      - 8080:8080